name: ejemplo_interfaz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/retrato.jpg
    - assets/images/nuevo.jpg
    - assets/images/piloto.png
    - assets/images/praga.jpg
    - assets/images/arquitectura.jpg
    - assets/images/dali.jpg
    - assets/images/grid1.jpg
    - assets/images/grid2.jpg
    - assets/images/grid3.jpg
    - assets/images/grid4.jpg
    - assets/images/grid5.jpg
    - assets/images/grid6.jpg
    - assets/images/grid7.jpg
    - assets/images/grid8.jpg
    - assets/images/grid9.jpg
    - assets/images/relax.jpg