name: anime_fetch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^9.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/icon/icono.png'
  adaptive_icon_background: 'assets/icon/icono.png'

flutter:
  uses-material-design: true

assets:
  - assets/
