name: drawer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/foto.png
    - assets/images/foto2.jpg
    - assets/images/foto3.jpg
    - assets/images/bird.png
    - assets/images/logo.png
    - assets/images/unnamed.png
