name: drawer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/foto.png
    - assets/images/foto2.jpg
    - assets/images/foto3.jpg
    - assets/images/bird.png
    - assets/images/logo.png
    - assets/images/unnamed.png
    - assets/images/pikachu.png
    - assets/images/squirtle.png
    - assets/images/charmander.png
    - assets/images/bulbasaur.png
    - assets/images/eevee.png
    - assets/images/meowth.png
    - assets/images/cunyao.png
    - assets/images/perrete.png
    - assets/images/pattern.png
    - assets/images/pattern2.png
    - assets/images/pattern3.jpg
    - assets/images/retrato.jpg
    - assets/images/nuevo.jpg
    - assets/images/piloto.png
    - assets/images/praga.jpg
    - assets/images/arquitectura.jpg
    - assets/images/dali.jpg
    - assets/images/jarl.jpg
    - assets/images/grid1.jpg
    - assets/images/grid2.jpg
    - assets/images/grid3.jpg
    - assets/images/grid4.jpg
    - assets/images/grid5.jpg
    - assets/images/grid6.jpg
    - assets/images/grid7.jpg
    - assets/images/grid8.jpg
    - assets/images/grid9.jpg
    - assets/images/relax.jpg
    - assets/images/oros1.jpg
    - assets/images/oros2.jpg
    - assets/images/oros3.jpg
    - assets/images/oros4.jpg
    - assets/images/oros5.jpg
    - assets/images/oros6.jpg
    - assets/images/oros7.jpg
    - assets/images/oros10.jpg
    - assets/images/oros11.jpg
    - assets/images/oros12.jpg
    - assets/images/bastos1.jpg
    - assets/images/bastos2.jpg
    - assets/images/bastos3.jpg
    - assets/images/bastos4.jpg
    - assets/images/bastos5.jpg
    - assets/images/bastos6.jpg
    - assets/images/bastos7.jpg
    - assets/images/bastos10.jpg
    - assets/images/bastos11.jpg
    - assets/images/bastos12.jpg
    - assets/images/espadas1.jpg
    - assets/images/espadas2.jpg
    - assets/images/espadas3.jpg
    - assets/images/espadas4.jpg
    - assets/images/espadas5.jpg
    - assets/images/espadas6.jpg
    - assets/images/espadas7.jpg
    - assets/images/espadas10.jpg
    - assets/images/espadas11.jpg
    - assets/images/espadas12.jpg
    - assets/images/copas1.jpg
    - assets/images/copas2.jpg
    - assets/images/copas3.jpg
    - assets/images/copas4.jpg
    - assets/images/copas5.jpg
    - assets/images/copas6.jpg
    - assets/images/copas7.jpg
    - assets/images/copas10.jpg
    - assets/images/copas11.jpg
    - assets/images/copas12.jpg